version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.2-apache
    container_name: web
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
       - ./magento-app:/var/www/html
    depends_on:
      - mysql
      - elasticsearch
    environment:
      PHP_MEMORY_LIMIT: 2048M
    command: >
      bash -c "echo 'memory_limit=2048M' > /usr/local/etc/php/conf.d/memory-limit.ini &&
               echo 'max_execution_time=1800' >> /usr/local/etc/php/conf.d/memory-limit.ini &&
               apache2-foreground"

  mysql:
    image: mariadb:10.6
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: magento
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  db-data:
  esdata:
